[package]
name = "TicketNFT"
version = "0.1.0"

[addresses]
<<<<<<< HEAD
moduleAddress = '0x6de994fec43fbb64b244f8e88e460576ab28239724d31d51cbfad8eb97271756'
=======
moduleAddress = '0x624ebfa1df2b252f89311e536dc783292446abfa0dd2c12512c3101ec733c39e'
>>>>>>> 5ae93a98b319f4d4b5702e58bab2640ac42a3998

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib", rev = "main" }
