[package]
name = "TicketNFT"
version = "1.0.0"

[addresses]
moduleAddress = "0xaad1cc4ea369a57f87ffaa82caf57053c8f47513a1efd0345f6b983faaacc9b2"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib", rev = "main" }
